# version: '3.8' 

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=energia_db
    ports:
      - "5432:5432"
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
    networks:
      - energia_net

  api:
    build: ./api
    container_name: api
    ports:
      - "5000:8000"
    environment:
      - DB_HOST=timescaledb
      - DB_NAME=energia_db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_PORT=5432
    depends_on:
      - timescaledb
    networks:
      - energia_net

  data_simulator:
    build: ./data_simulator
    container_name: data_simulator
    depends_on:
      - api
    networks:
      - energia_net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - timescaledb
    networks:
      - energia_net

networks:
  energia_net:
    driver: bridge

volumes:
  timescaledb-data:
